spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/ssy55ssy/SpringCloud/
          searchPaths: respo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/